program
	int pontuacao, pontuacaoMaxima, disponibilidade;
	string pontuacaoMinima;
	disponibilidade = "Sim";
	pontuacaoMinima = 50;
	pontuacaoMaxima = 100;
	/* Entrada de dados
	Verifica aprovação de candidatos
	do
	print("Pontuacao Candidato: ");
		scan(pontuacao);
		print("Disponibilidade Candidato: ");
		scan(disponibilidade);

		if ((pontuação > pontuacaoMinima) and (disponibilidade=="Sim") then
			print("Candidato aprovado");
		else
			print("Candidato reprovado")
		end
	while (pontuação >= 0) end
end
